// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-KH97pL82pKRiB_tRjJRGwwraPbKiKo',
    appId: '1:603178779348:web:08df817bdbdb6722db3141',
    messagingSenderId: '603178779348',
    projectId: 'application-cd7c3',
    authDomain: 'application-cd7c3.firebaseapp.com',
    storageBucket: 'application-cd7c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-UPu44uE8S3y9AbAOE59iF0zt-Q0kU3M',
    appId: '1:603178779348:android:83892e6744919b1adb3141',
    messagingSenderId: '603178779348',
    projectId: 'application-cd7c3',
    storageBucket: 'application-cd7c3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg-KH97pL82pKRiB_tRjJRGwwraPbKiKo',
    appId: '1:603178779348:web:0dba4951ccdebc8adb3141',
    messagingSenderId: '603178779348',
    projectId: 'application-cd7c3',
    authDomain: 'application-cd7c3.firebaseapp.com',
    storageBucket: 'application-cd7c3.firebasestorage.app',
  );
}
